/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xxl.job.executor.simple;

import org.junit.Test;
import static org.junit.Assert.*;

public class XXLApplication {

    public static void main(String[] args) {

    }
}
